/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookFay.UI;

import BookFay.Controller.*;
import BookFay.DBconnection.BookFayConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Qhris
 */
public class StudentUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentUI
     */
    public StudentUI() {
        initComponents();
    }
  public void SwitchPanel(JPanel panel){
        MainTab.removeAll();
        MainTab.add(panel);
        MainTab.repaint();
        MainTab.revalidate();
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        kButton8 = new keeptoo.KButton();
        kButton6 = new keeptoo.KButton();
        kButton9 = new keeptoo.KButton();
        MainTab = new javax.swing.JTabbedPane();
        RequestBook = new javax.swing.JPanel();
        CallNo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        kButton11 = new keeptoo.KButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CallNo1 = new javax.swing.JTextField();
        complaint = new javax.swing.JPanel();
        kButton4 = new keeptoo.KButton();
        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setForeground(new java.awt.Color(102, 0, 102));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 0));
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("BOOKFAY- Library Management System");

        kButton8.setText("Request Book");
        kButton8.setBorderPainted(false);
        kButton8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        kButton8.setkAllowTab(false);
        kButton8.setkEndColor(new java.awt.Color(0, 51, 102));
        kButton8.setkFillButton(false);
        kButton8.setkHoverEndColor(new java.awt.Color(153, 0, 153));
        kButton8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton8.setkIndicatorColor(new java.awt.Color(204, 204, 204));
        kButton8.setkIndicatorThickness(3);
        kButton8.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton8.setkSelectedColor(new java.awt.Color(0, 51, 204));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });

        kButton6.setText("Logout");
        kButton6.setBorderPainted(false);
        kButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kButton6.setkAllowTab(false);
        kButton6.setkEndColor(new java.awt.Color(0, 51, 102));
        kButton6.setkFillButton(false);
        kButton6.setkHoverEndColor(new java.awt.Color(153, 0, 153));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton6.setkIndicatorColor(new java.awt.Color(204, 204, 204));
        kButton6.setkIndicatorThickness(3);
        kButton6.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton6.setkSelectedColor(new java.awt.Color(0, 51, 204));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        kButton9.setText("Write a Complain");
        kButton9.setBorderPainted(false);
        kButton9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        kButton9.setkAllowTab(false);
        kButton9.setkEndColor(new java.awt.Color(0, 51, 102));
        kButton9.setkFillButton(false);
        kButton9.setkHoverEndColor(new java.awt.Color(153, 0, 153));
        kButton9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton9.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton9.setkIndicatorColor(new java.awt.Color(204, 204, 204));
        kButton9.setkIndicatorThickness(3);
        kButton9.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton9.setkSelectedColor(new java.awt.Color(0, 51, 204));
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(kButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(kButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(kButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 650));

        MainTab.setBackground(new java.awt.Color(255, 255, 255));
        MainTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MainTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        MainTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        MainTab.setAutoscrolls(true);

        RequestBook.setBackground(new java.awt.Color(255, 255, 255));
        RequestBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CallNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallNoActionPerformed(evt);
            }
        });
        RequestBook.add(CallNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 371, 41));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Book Name:");
        RequestBook.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, 20));

        kButton11.setForeground(new java.awt.Color(0, 102, 153));
        kButton11.setText("Request");
        kButton11.setBorderPainted(false);
        kButton11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        kButton11.setkAllowTab(false);
        kButton11.setkBackGroundColor(new java.awt.Color(0, 0, 102));
        kButton11.setkEndColor(new java.awt.Color(0, 51, 102));
        kButton11.setkHoverEndColor(new java.awt.Color(0, 51, 102));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton11.setkHoverStartColor(new java.awt.Color(51, 204, 255));
        kButton11.setkIndicatorColor(new java.awt.Color(204, 204, 204));
        kButton11.setkIndicatorThickness(3);
        kButton11.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton11.setkSelectedColor(new java.awt.Color(0, 51, 204));
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });
        RequestBook.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 370, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 255));
        jLabel14.setText("Request Book");
        jLabel14.setIconTextGap(10);
        RequestBook.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 110, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Author:");
        RequestBook.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 100, 20));

        CallNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallNo1ActionPerformed(evt);
            }
        });
        RequestBook.add(CallNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 371, 41));

        MainTab.addTab("", RequestBook);

        complaint.setBackground(new java.awt.Color(255, 255, 255));
        complaint.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                complaintFocusGained(evt);
            }
        });
        complaint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton4.setForeground(new java.awt.Color(0, 102, 153));
        kButton4.setText("Submit");
        kButton4.setBorderPainted(false);
        kButton4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        kButton4.setkAllowTab(false);
        kButton4.setkBackGroundColor(new java.awt.Color(0, 0, 102));
        kButton4.setkEndColor(new java.awt.Color(0, 51, 102));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 51, 102));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(51, 204, 255));
        kButton4.setkIndicatorColor(new java.awt.Color(204, 204, 204));
        kButton4.setkIndicatorThickness(3);
        kButton4.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton4.setkSelectedColor(new java.awt.Color(0, 51, 204));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        complaint.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 410, -1));

        MainTab.addTab("", complaint);

        kGradientPanel1.add(MainTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 890, 620));

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        close.setBackground(new java.awt.Color(0, 0, 102));
        close.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(0, 0, 51));
        close.setText("x");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(0, 0, 51));
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1224, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimize)
                    .addComponent(close))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
        SwitchPanel(RequestBook);
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
       new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_kButton6ActionPerformed

    private void CallNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CallNoActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
//            int status=0;
//            try{
//                String Message                
//                if(Message.equals("")){
//                 JOptionPane.showMessageDialog(StudentUI.this,"Sorry, Form is Empty");
//
//        }else{
//                       
//		Connection con = BookFayConnection.getConnection();
//		PreparedStatement ps=con.prepareStatement("insert into complaint(message) values(?)");
//		ps.setString(1,Message);
//                status = ps.executeUpdate();
//		con.close();
//
//                JOptionPane.showMessageDialog(StudentUI.this,"Book added successfully!");
//
//        }
//	}catch(Exception e){System.out.println(e);}
//
//                        
//			
// 	
//			
    }//GEN-LAST:event_kButton4ActionPerformed

    private void complaintFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_complaintFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_complaintFocusGained

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int x=JOptionPane.showConfirmDialog(null,"Are you sure to quit","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(x==0) System.exit(0);
        else return;
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int y = evt.getYOnScreen();
        int x = evt.getXOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged
    int xx, yy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        SwitchPanel(complaint);        // TODO add your handling code here:
    }//GEN-LAST:event_kButton9ActionPerformed

    private void CallNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CallNo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CallNo;
    private javax.swing.JTextField CallNo1;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JPanel RequestBook;
    private javax.swing.JLabel close;
    private javax.swing.JPanel complaint;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton6;
    private keeptoo.KButton kButton8;
    private keeptoo.KButton kButton9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables
}
